In [1]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from numpy.linalg import inv

ЗАДАНИЕ 1

Входные данные: матрицы  в виде numpy-массивов. Гарантируется, что их можно перемножить в порядке AxBxC.

Результат: напишите функцию multiplication_order(A, B, C), которая вернёт строку "(AxB)xC", если количество умножений элементов матриц при умножении  меньше либо равно количеству умножений, если выполнять их в порядке. В противном случае верните строку "Ax(BxC)".

In [2]:
# Пример входных данных:
A = np.array([[1,2]])
B = np.array([[2], [1]])
C = np.array([[5]])

Пример результата: “(AxB)xC”

In [3]:
def multiplication_order(A, B, C):
    mult_num_A_B = A.shape[0]*B.shape[1]
    new_mat = A@B 
    mult_num_new_mat_C = new_mat.shape[0]*B.shape[1]
    mult_sum_1 = mult_num_A_B + mult_num_new_mat_C
     
    
    
    mult_num_B_C = B.shape[0]*C.shape[1]
    new_mat = B@C
    mult_num_new_mat_A = A.shape[0]*new_mat.shape[1]
    mult_sum_2 = mult_num_B_C + mult_num_new_mat_A
    
    
    
    if mult_sum_1 <= mult_sum_2:
        return '(AxB)xC'
    else:
        return 'Ax(BxC)'
    

In [4]:
multiplication_order(A, B, C)


'(AxB)xC'

ЗАДАНИЕ 2

Входные данные: матрица признаков  в виде numpy-массива и вектор цен . Количество строк в матрице  совпадает с количеством элементов в векторе . Каждая строка матрицы описывает признаки одной квартиры, а соответствующий элемент в  равен цене квартиры.

Результат: напишите функцию best_worst(X, Y), которая вернёт два числа: max_corr_idx (номер признака, наиболее коррелирующего с ценой) и min_corr_idx (номер признака, наименее коррелирующего с ценой). Учитывайте, что корреляция имеет знак, а сила корреляции зависит от абсолютного значения — нужно вернуть наибольший и наименьший признаки по абсолютному значению.

In [9]:
data = pd.read_csv('data/Math_project1.csv', encoding='utf-8')

In [10]:
data.head()

Комнаты  Площадь  Этаж  Центр?  Спальный1?  Спальный 2?  Цена
0        3       51     3       0           1            0  2200
1        1       30     1       0           1            0  1600
2        2       45     2       0           1            0  1900
3        3       55     1       0           1            0  2000
4        1       45     3       1           0            0  4500

In [11]:
C = data.corr(method='pearson')
C

Комнаты   Площадь      Этаж        Центр?  Спальный1?  \
Комнаты      1.000000e+00  0.660935  0.248747  1.328697e-17    0.221601   
Площадь      6.609352e-01  1.000000  0.098311  6.759426e-01   -0.210376   
Этаж         2.487469e-01  0.098311  1.000000 -2.886751e-02   -0.574612   
Центр?       1.328697e-17  0.675943 -0.028868  1.000000e+00   -0.462910   
Спальный1?   2.216013e-01 -0.210376 -0.574612 -4.629100e-01    1.000000   
Спальный 2? -2.216013e-01 -0.415425  0.601338 -4.629100e-01   -0.571429   
Цена         2.476680e-01  0.866628  0.040698  9.377178e-01   -0.412126   

             Спальный 2?      Цена  
Комнаты        -0.221601  0.247668  
Площадь        -0.415425  0.866628  
Этаж            0.601338  0.040698  
Центр?         -0.462910  0.937718  
Спальный1?     -0.571429 -0.412126  
Спальный 2?     1.000000 -0.456032  
Цена           -0.456032  1.000000

In [12]:
np.linalg.matrix_rank(C)

6

In [13]:
data.columns

Index(['Комнаты', 'Площадь', 'Этаж', 'Центр?', 'Спальный1?', 'Спальный 2?',
       'Цена'],
      dtype='object')

In [14]:
X =  data.loc[:,['Комнаты', 'Площадь', 'Этаж', 'Центр?', 'Спальный1?', 'Спальный 2?']].values
Y = data['Цена'].values

In [15]:
def best_worst(x, y):
    A = np.concatenate([y.reshape((y.shape[0], 1)), x], axis=1).T
    B = np.abs(np.corrcoef(A)[0][1:])
    return np.argmax(B), np.argmin(B)

In [16]:
best_worst(X,Y)

(3, 2)

ЗАДАНИЕ 3

Входные данные: матрица признаков  в виде numpy-массива.

Результат: напишите функцию corr_rank(X), возвращающую одно число — ранг корреляционной матрицы.

In [17]:
def corr_rank(X):
    a = X.T
    c = np.corrcoef(a)
    return np.linalg.matrix_rank(c)

In [29]:
corr_rank(X)

5

ЗАДАНИЕ 4

Входные данные: матрица  в виде numpy-массива

Результат: напишите функцию inverse_matrix(A), которая вернёт None, если матрица необратима (то есть её определитель по абсолютному значению меньше ), либо вернёт обратную матрицу в виде numpy-массива.

In [18]:
def inverse_matrix(A):
    if abs(np.linalg.det(A)) > 0.001:
        return np.linalg.inv(A)
     
   

In [19]:
# Пример входных данных:
A = np.array([[1, 2], [2, 1]])

Пример результата:
array([[-0.33333333, 0.66666667],
[ 0.66666667, -0.33333333]])

In [20]:
inverse_matrix(A)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [21]:
np.linalg.det(A)

-2.9999999999999996

In [22]:
np.linalg.inv(A)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

ЗАДАНИЕ 5

Построить линейную модель методом OLS.

Входные данные: матрица признаков X в виде numpy-массива и вектор цен y в виде numpy-массива. X имеет форму (m, n) — m строк, по строке на каждую квартиру, n признаков для каждой квартиры. Y имеет форму (m), это вектор из m элементов — цены всех m квартир.

Результат: напишите функцию fit_model(X, y), которая вернёт numpy-массив с оптимальными коэффициентами a

In [26]:
X =  data.loc[:,['Комнаты', 'Площадь', 'Этаж', 'Центр?', 'Спальный1?', 'Спальный 2?']].values
y = data['Цена'].values

In [27]:
def fit_model(X, y):
    return ((inv((X.T)@X))@X.T)@y

In [28]:
fit_model(X, y)

array([-574.12295766,   65.33255763,  141.80223878, 1566.16246224,
         12.32450391, -315.34552489])